{
 "title": "Meshtastic",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(meshtastic_mesh_packets_received_count,job)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "relay",
    "query": {
     "query": "label_values(meshtastic_mesh_packets_received_count{job=\"$job\"},relayNode)"
    }
   },
   { "name": "filters" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last hour stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[1h])) by (relayNode) != 0)",
     "legendFormat": "Unique Relays"
    },
    {
     "expr": "count(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[1h])) by (from) != 0)",
     "legendFormat": "Nodes Online"
    },
    {
     "expr": "floor(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[1h])) * 3600)",
     "legendFormat": "Packets RX"
    }
   ]
  },
  {
   "title": "Last 24 hours stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[24h])) by (relayNode) != 0)",
     "legendFormat": "Unique Relays"
    },
    {
     "expr": "count(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[24h])) by (from) != 0)",
     "legendFormat": "Nodes Online"
    },
    {
     "expr": "floor(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[24h])) * 3600 * 24)",
     "legendFormat": "Packets RX"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Packets received by relays over time",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[$__rate_interval])) by (relayNode) * $interval",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received packets SNR",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_snr_bucket{job=\"$job\"}[$__rate_interval])) * $interval",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received packets RSSI",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_rssi_bucket{job=\"$job\"}[$__rate_interval])) * $interval",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets received by relays",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packets_received_count{job=\"$job\"}[$__range])) by (relayNode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets received by relays $interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[$__rate_interval])) * 3600",
     "legendFormat": "Total packets rx"
    }
   ]
  },
  {
   "title": "Relay Diversity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "count(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[$__rate_interval])) by (relayNode) != 0)",
     "legendFormat": "Unique relays"
    }
   ]
  },
  {
   "title": "Received packets hops",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_hops_bucket{job=\"$job\"}[$__rate_interval])) * $interval",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets received by relays",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[1h])) by (relayNode) * 3600",
     "legendFormat": "Relayed by {{ relayNode }}"
    }
   ]
  },
  {
   "title": "Nodes Online Hourly",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 24 },
   "targets": [
    {
     "expr": "count(sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\"}[1h])) by (from) != 0)",
     "legendFormat": "online nodes in last 1h"
    }
   ]
  },
  {
   "title": "Received packets size",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_size_bucket{job=\"$job\"}[$__rate_interval])) * $interval",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received packets payload size",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_payload_size_bucket{job=\"$job\"}[$__rate_interval])) * $interval",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay $relay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "relay",
   "collapsed": true,
   "panels": [
    {
     "title": "Relayed nodes",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(rate(meshtastic_mesh_packets_received_count{job=\"$job\",relayNode=~\"$relay\"}[$__rate_interval])) by (from)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received packets SNR",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 32 },
     "targets": [
      {
       "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_snr_bucket{job=\"$job\", relayNode=~\"$relay\"}[$__rate_interval])) * 3600",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received packets RSSI",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_rssi_bucket{job=\"$job\", relayNode=~\"$relay\"}[$__rate_interval])) * 3600",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received packets hops",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
     "targets": [
      {
       "expr": "sum by(le) (rate(meshtastic_mesh_packets_received_hops_bucket{job=\"$job\", relayNode=~\"$relay\"}[$__rate_interval])) * 3600",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Possible Relay Names",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
     "targets": [
      {
       "expr": "sum(meshtastic_mesh_packets_received_hops_bucket{job=\"$job\", le=\"0.0\", from=~\"![0-9a-fA-F]{6}$relay\"}) by (from,relayNode) > 0",
       "legendFormat": "__auto"
      },
      { "expression": "A", "reducer": "max", "settings": { "mode": "dropNN" }, "type": "reduce" }
     ]
    }
   ]
  }
 ]
}